services:
  sqli:
    image: python:3.11
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/sqli-challenge
    command: |
      sh -c "
        cd /sqli-challenge &&
        pip install -r requirements.txt &&
        python app.py
      "
